In [1]:
import numpy as np
import pandas as pd
import pickle

In [2]:
ohe_sex = pickle.load(open(r'E:\New folder (2)\pipeline\pickled_file\ohe_sex.pkl', 'rb'))
ohe_embarked = pickle.load(open(r'E:\New folder (2)\pipeline\pickled_file\ohe_embarked.pkl', 'rb'))
dt = pickle.load(open(r'E:\New folder (2)\pipeline\pickled_file\dt.pkl', 'rb'))

In [3]:
#assuming user_input

test_input = np.array([3, "male",	41,	0,	0	,7.1250	,"C"],dtype=object).reshape(1,7)
test_input

array([[3, 'male', 41, 0, 0, 7.125, 'C']], dtype=object)

In [4]:
test_input_sex = ohe_sex.transform(test_input[:, 1:2])
test_input_embarked = ohe_embarked.transform(test_input[:, -1:])
test_input_embarked

array([[1., 0., 0.]])

In [5]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input[:,[2]],test_input_sex,test_input_embarked),axis =1)

In [6]:
test_input_transformed = pd.DataFrame(test_input_transformed,columns=["Pclass","SibSp","Parch","Fare","Age","Female","Male","C","Q","S"])
test_input_transformed

Pclass SibSp Parch   Fare Age Female Male    C    Q    S
0      3     0     0  7.125  41    0.0  1.0  1.0  0.0  0.0

In [7]:
dt.predict(test_input_transformed)

array([0], dtype=int64)